# 사이트 정보
[site]
  site_id = "a962dafe-ebd2-4257-919f-0ac22c2b5237"
  site_url = "https://memoku.netlify.app/"
  admin_url = "https://app.netlify.com/sites/memoku/"

# 빌드 설정
[build]
  publish = "dist"  # 배포할 디렉토리 경로
  command = "pnpm build"  # 빌드 명령어

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[edge_functions]]
  path = "/*"
  function = "block-bots"
